name: Publish to GitHub Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: ./gradlew build
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ github.actor }}
        GITHUB_USERNAME: ${{ github.token }}
      run: ./gradlew publish