name: Publish package to the Maven Central Repository and GitHub Packages
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Using Caches
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Grant Execute Permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to the Maven Central Repository
        run: ./gradlew publish
        env:
          VERSION: ${{ github.event.release.tag_name }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.TOKEN }}